# Workflow which will build charibot and "cross-compile"/jlink it for multiple OS and architecture
name: build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        type: string

jobs:
  jlink:
    env:
      JDK_BASE_URL: "https://download.java.net/java/GA/jdk25.0.1/2fbf10d8c78e40bd87641c434705079d/8/GPL/"
      build_os: linux
      build_arch: x64
      build_pkg: tar.gz

    strategy:
      matrix:
        os:    [linux, windows, macos]
        arch:  [aarch64, x64]
        include:
          - os: linux
            pkg: tar.gz
          - os: windows
            pkg: zip
          - os: macos
            pkg: tar.gz
        exclude:
          - os: windows
            arch: aarch64

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download target OS+Arch JDK
        # curl --output /tmp/jdk.tar.gz \
        # https://download.java.net/java/GA/jdk25.0.1/2fbf10d8c78e40bd87641c434705079d/8/GPL/openjdk-25.0.1_linux-x64_bin.tar.gz
        run: curl --output ${{ runner.temp }}/jdk.${{ matrix.pkg }} ${{ env.JDK_BASE_URL }}/openjdk-25.0.1_${{ matrix.os }}-${{ matrix.arch }}_bin.${{ matrix.pkg }}

      # In order to avoid knowing the directory structure within the different target OS+Arch archives,
      # using setup-java action to unpack the target OS+Arch archive (probably performs unpack + JAVA_HOME + PATH)
      # to be able to easily reference the target JDK location as $JAVA_HOME
      - uses: actions/setup-java@v4
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/jdk.${{ matrix.pkg }}
          java-version: '25'
          architecture: ${{ matrix.arch }}

      - name: Copy target JDK
        run: cp -r ${{ env.JAVA_HOME }} ${{ runner.temp }}/targetjdk

      - name: Download build environment JDK
        if: ${{ matrix.os != env.build_os || matrix.arch != env.build_arch }}
        run: curl --output ${{ runner.temp }}/buildjdk.${{ env.build_pkg }} ${{ env.JDK_BASE_URL }}/openjdk-25.0.1_${{ env.build_os }}-${{ env.build_arch }}_bin.${{ env.build_pkg }}

      - uses: actions/setup-java@v4
        if: ${{ matrix.os != env.build_os || matrix.arch != env.build_arch }}
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/buildjdk.${{ env.build_pkg}}
          java-version: '25'
          architecture: ${{ env.build_arch }}

      - name: Set version in pom.xml
        run: mvn -B versions:set -DnewVersion="${{ inputs.version }}"

      - name: Run build
        run: mvn -B clean verify -Dsource.jdk=$(dirname $(find ${{ runner.temp }}/targetjdk -name jmods)) -Dos.arch.classifier=${{ matrix.os }}-${{ matrix.arch }}

      - name: Prepare directory to package
        run: mkdir to-package && mv target/maven-jlink/classifiers/${{ matrix.os }}-${{ matrix.arch }} to-package/charibot-${{ inputs.version }}

      - name: Determine file type of packaged java binary
        run: file $(find to-package/ -regex ".*/bin/java\(.exe\)?$")

      # upload-artifact doesn't preserve the executable bit information of files,
      # so creating a zip file which preserves the executable bits,
      # and then tell upload-artifact to zip this zip file instead of the files within the zip... sigh.
      - name: Create zip, preserving executable bits
        run: cd to-package && zip -r charibot-${{ inputs.version }}-${{ matrix.os }}-${{ matrix.arch }}.zip charibot-${{ inputs.version }} && cd ..

      - uses: actions/upload-artifact@v4
        with:
          name: wrapped-zip-charibot-${{ inputs.version }}-${{ matrix.os }}-${{ matrix.arch }}
          path: to-package/charibot-${{ inputs.version }}-${{ matrix.os }}-${{ matrix.arch }}.zip
