name: build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        type: string

jobs:
  jlink:
    env:
      LINUX_JDK_URL:   'https://download.java.net/java/early_access/jdk23/34/GPL/openjdk-23-ea+34_linux-x64_bin.tar.gz'
      MACOS_JDK_URL:   'https://download.java.net/java/early_access/jdk23/34/GPL/openjdk-23-ea+34_macos-aarch64_bin.tar.gz'
      WINDOWS_JDK_URL: 'https://download.java.net/java/early_access/jdk23/34/GPL/openjdk-23-ea+34_windows-x64_bin.zip'

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Download JDK Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: curl -L -o ${{ runner.temp }}/jdk.tar.gz ${{ env.LINUX_JDK_URL }}

      - name: Download JDK MacOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: curl -L -o ${{ runner.temp }}/jdk.tar.gz ${{ env.MACOS_JDK_URL }}

      - name: Download JDK Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: curl -L -o ${{ runner.temp }}/jdk.zip ${{ env.WINDOWS_JDK_URL }}

      - uses: actions/setup-java@v4
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/jdk.tar.gz
          java-version: '23'
          architecture: x64 # note, macos aarch64. But maybe setup-java doesn't not look at this field if using 'jdkFile'

      - uses: actions/setup-java@v4
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/jdk.zip
          java-version: '23'
          architecture: x64

      - name: version
        run: mvn -B versions:set -DnewVersion="${{ inputs.version }}"

      - name: build
        run: mvn -B clean verify

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: target/*.zip

